name: hivebox_ci
on:
  push:
    branches:
      - main
    paths:
     - 'phase2/**'
permissions:
  contents: read
  checks: write     
  
jobs: 
   build:
     runs-on: ubuntu-latest 
     steps:
     - uses: actions/checkout@v4 
        
     - name: checkout python
       uses: actions/setup-python@v3
       with:
        python-version: "3.10"
        
     - name: Install Python dependencies
       run: |  #unittest-xml-reporting for test report, pylint for test
        python -m pip install --upgrade pip
        pip install flask requests python-dateutil pylint unittest-xml-reporting
        

     - name: pylint check
       working-directory: phase2
       run: |
          pylint hivebox_v2.py
          

     - name: install hadolint 
       run: |
        wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
        chmod +x /usr/local/bin/hadolint
        
     - name: Lint Dockerfile
       working-directory: phase2
       run: hadolint dockerfile

     - name: build docker
       working-directory: phase2
       run: |
        docker build -t hivebox .

     - name: Run unit tests
       run: python -m xmlrunner discover -s phase2 -p "unit_test.py" -o test-results

     - name: run docker 
       run: |
         docker run -d -p 5000:5000 --name hivebox hivebox
         sleep 5

     - name: Test /version endpoint
       run: |
        RESPONSE=$(curl -s http://localhost:5000/version)
        echo "Response: $RESPONSE"
        echo "$RESPONSE" | grep '"version": "1.0.0"'

     - name: Publish Test Report
       uses: mikepenz/action-junit-report@v3
       if: success() || failure() # always run even if the previous step fails
       with:
        report_paths: 'test-results/**/*.xml'
        detailed_summary: true
        include_passed: true
        
        
   
    
